"""itinerary_display.py — Renders AI-generated itinerary and advanced features."""

import streamlit as st


def render_itinerary(itinerary_md: str, destination: str, days: int):
    """Display the AI-generated itinerary in a formatted card."""
    st.markdown(f"### 🗺️ Your {days}-Day {destination} Itinerary")
    st.markdown(
        "<div style='padding:1.5rem; border-radius:12px; "
        "background: linear-gradient(135deg, #0f172a, #1e1b4b); "
        "border: 1px solid #6366f1; margin-bottom:1rem;'>"
        "<p style='color:#a5b4fc; font-size:0.85rem; margin:0;'>✨ AI-Generated by Groq Llama 3 · Personalized for your interests</p>"
        "</div>",
        unsafe_allow_html=True,
    )
    st.markdown(itinerary_md)


def render_packing_list(packing_md: str, destination: str):
    """Display the AI-generated packing list."""
    st.markdown(f"### 🎒 Packing List for {destination}")
    st.markdown(packing_md)


def render_local_tips(tips_md: str, destination: str):
    """Display local tips."""
    st.markdown(f"### 🗺️ Local Insider Tips — {destination}")
    st.markdown(tips_md)


def render_budget_analysis(analysis_md: str, budget_inr: float, days: int):
    """Display budget analysis with visual indicator."""
    daily = budget_inr / days if days > 0 else 0
    st.markdown("### 💰 Budget Analysis")
    col1, col2 = st.columns(2)
    col1.metric("Total Budget", f"₹{budget_inr:,.0f} INR")
    col2.metric("Daily Budget", f"₹{daily:,.0f} INR/day")
    st.markdown(analysis_md)
